<!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Página inicial do painel</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Painel Administrativo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li <?php if(isUrl('dashboard')) { ?>
            <?= 'class="active"' ?>
            <?php } ?> >
            <a class="nav-link" href="<?=HOME?>">Home <span class="sr-only">(atual)</span></a>
          </li>
          <li <?php if(isUrl('users')) { ?>
            <?= 'class="active"' ?>
            <?php } ?> >
            <a class="nav-link" href="<?=HOME . '/admin/users/list'?>">Usuário<span class="sr-only">(atual)</span></a>
          </li>
          <li <?php if(isUrl('products')) { ?>
            <?= 'class="active"' ?>
            <?php } ?> >
            <a class="nav-link" href="<?=HOME . '/admin/products/list'?>">Produtos<span class="sr-only">(atual)</span></a>
          </li> 
          <li <?php if(isUrl('categories')) { ?>
            <?= 'class="active"' ?>
            <?php } ?> >
            <a class="nav-link" href="<?=HOME . '/admin/categories/list'?>">Categorias</a>
          </li> 

        </ul>
        <div class="ml-auto ">
          <a class="btn btn-danger" href="<?=HOME . '/auth/logout'?>">Sair</a>
        </div>
      </div>
    </nav>

    <!-- Main start -->

    <main class="container" style="margin-top: 5em";>