<?php require VIEWS . '/includes/header.phtml'; ?>

        <div class="row mb-3">
            <div class="">
                <h1>Produtos</h1>
            </div>
            <a href="<?=HOME . '/admin/products/save';?>" class="btn btn-md btn-primary mb-3 ml-auto">
                Cadastrar Produto
            </a>
        </div>
        <div class="row">
            <?php require VIEWS . '/includes/message.phtml'; ?>
        </div>
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>#</th>
                        <th>Produto</th>
                        <th>Preço</th>
                        <th>Categoria</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($products as $product) { ?>
                    <tr>
                        <td>
                            <?php if($product['image']): ?>
                                <img src="<?= HOME . '/assets/uploads/thumbs/' . $product['image']; ?>" alt="thumb" width="100" heigth="100">
                            <?php else: ?>
                                <img src="https://place-hold.it/100x100/666/fff.png/000" alt="thumb">
                            <?php endif; ?>
                        </td>
                        <td><?=$product['id']?></td>
                        <td><?=$product['name']?></td>
                        <td><?=$product['price']?></td>
                        <td><p class="badge badge-success"><?=$product['category']?></p></td>
                        <td>
                            <a href="<?=HOME . '/admin/products/edit/'. $product['id'] ;?>" class="btn btn-sm btn-warning">Editar</a>
                            <a href="<?=HOME . '/admin/products/remove/'. $product['id'] ;?>" class="btn btn-sm btn-danger">Remover</a>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    
<?php require VIEWS . '/includes/footer.phtml'; ?>