<?php require VIEWS . '/includes/header.phtml'; ?>

        <div class="row mb-3">
            <div class="">
                <h1>Cadastrar produtos</h1>
            </div>
            <a href="<?=HOME . '/admin/products/list';?>" class="btn btn-md btn-danger mb-3 ml-auto">
                Voltar
            </a>
        </div>
        <div class="row">
            <?php require VIEWS . '/includes/message.phtml'; ?>
        </div>
        <div class="">
            <form action="<?=HOME . '/admin/products/save'?>" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                        <label for="exampleInputPassword1">Nome</label>
                        <input type="text" class="form-control" placeholder="Nome" name="name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Slug (Ex: product-um)</label>
                        <input type="text" class="form-control" placeholder="Slug" name="slug">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Preço</label>
                        <input type="text" class="form-control" placeholder="Preço" name="price">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Quantidade</label>
                        <input type="number" class="form-control" placeholder="Quantidade" name="amount">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Descrição</label>
                        <input type="text" class="form-control" placeholder="Descrição" name="description">
                    </div>

                    <div class="form-group">
                        <label>Categoria deste Produto</label>
                        <select name="category_id">
                            <?php foreach($categories as $category) { ?>
                                <option value="<?=$category['id']?>"><?=$category['name']?></option>
                            <?php  } ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Imagens do produto</label>
                        <input type="file" class="form-control" name="images[]" multiple>
                    </div>

                <button type="submit" class="btn btn-primary">Salvar produto</button>
            </form>
        </div>
    
<?php require VIEWS . '/includes/footer.phtml'; ?>