<?php require VIEWS . '/includes/header.phtml'; ?>

        <div class="row">
            <div class="col-md-12">
                <h1>Cadastrar produtos</h1>
            </div>
        </div>
        <div class="row">
            <?php require VIEWS . '/includes/message.phtml'; ?>
        </div>
        <div class="">
            <a href="<?=HOME . '/?url=categories/list';?>" class="btn btn-md btn-danger mb-3">
                Voltar
            </a>
            <form action="<?=HOME . '?url=categories/save'?>" method="POST">

                    <div class="form-group">
                        <label for="exampleInputPassword1">Nome(*)</label>
                        <input type="text" class="form-control" placeholder="Nome" name="name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Descrição(*)</label>
                        <input type="text" class="form-control" placeholder="Descrição" name="description">
                    </div>

                <button type="submit" class="btn btn-primary">Salvar categoria</button>
            </form>
        </div>
    
<?php require VIEWS . '/includes/footer.phtml'; ?>