<?php require VIEWS . '/site/header.phtml'; ?>

    <main role="main">

        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <?php if(isset($product['images']) && count($product['images']) > 0) { ?>

                <img class="img-fluid" src="<?= HOME . '/assets/uploads/thumbs/' . $product['images'][0]['image']; ?>" alt="">

              <?php } else { ?>

                <img class="img-fluid" src="http://placehold.it/360x250" alt="">

              <?php } ?>
            </div>
            <div class="col-md-6">
              <h1><?= $product ['name'];?></h1>
              <p><?= $product ['description'];?></p>
              <h5 class="font-weight-bold">R$ <?=number_format($product['price'], 2, ',', '.')?></h5>
            </div>
          </div>
        </div>

    </main>

<?php require VIEWS . '/site/footer.phtml'; ?>