<?php require VIEWS . '/includes/header.phtml'; ?>

        <div class="row mb-3">
            <div>
                <h1>Usuários</h1>
            </div>
            <a href="<?=HOME . '/admin/users/save';?>" class="btn btn-md btn-primary mb-3 ml-auto">
                Criar usuário
            </a>
        </div>
        <div class="row">
            <?php require VIEWS . '/includes/message.phtml'; ?>
        </div>
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Criado Em</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($users as $user) { ?>
                    <tr>
                        <td><?=$user['id']?></td>
                        <td><?=$user['name']?></td>
                        <td><?=$user['email']?></td>
                        <td><?=date("d/m/Y H:i:s", strtotime($user['created_at']))?></td>
                        <td>
                            <a href="<?=HOME . '/admin/users/edit/'. $user['id'] ;?>" class="btn btn-sm btn-warning">Editar</a>
                            <a href="<?=HOME . '/admin/users/remove/'. $user['id'] ;?>" class="btn btn-sm btn-danger">Remover</a>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    
<?php require VIEWS . '/includes/footer.phtml'; ?>