<?php require VIEWS . '/includes/header.phtml'; ?>

        <div class="row">
            <div class="col-md-12">
                <h1>Usuários</h1>
            </div>
        </div>
        <div class="row">
            <?php require VIEWS . '/includes/message.phtml'; ?>
        </div>
        <div class="row">
            <a href="<?=HOME . '/?url=users/save';?>" class="btn btn-md btn-primary mb-3">
                Criar usuário
            </a>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Criado Em</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($users as $user) { ?>
                    <tr>
                        <td><?=$user['id']?></td>
                        <td><?=$user['name']?></td>
                        <td><?=$user['email']?></td>
                        <td><?=date("d/m/Y H:i:s", strtotime($user['created_at']))?></td>
                        <td>
                            <a href="<?=HOME;?>/?url=users/edit&id=<?=$user['id'];?>" class="btn btn-sm btn-warning">Editar</a>
                            <a href="<?=HOME;?>/?url=users/remove&id=<?=$user['id'];?>" class="btn btn-sm btn-danger">Remover</a>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    
<?php require VIEWS . '/includes/footer.phtml'; ?>