<?php require VIEWS . '/includes/header.phtml'; ?>

        <div class="row">
            <div class="col-md-12">
                <h1>Usuários</h1>
            </div>
        </div>
        <div class="">
            <a href="<?=HOME . '/?url=users/list';?>" class="btn btn-md btn-danger mb-3">
                Voltar
            </a>
            <?php require VIEWS . '/includes/message.phtml'; ?>   
            <form action="<?=HOME . '?url=users/save'?>" method="POST">
                <div class="form-group">
                        <label for="exampleInputPassword1">Nome(*)</label>
                        <input type="texte" class="form-control" placeholder="Nome" name="name" value="<?php if(isset($_POST['name']))?>">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Endereço de email(*)</label>
                        <input type="email" class="form-control" aria-describedby="emailHelp" placeholder="Seu email" name="email" value="<?php if(isset($_POST['email']))?>">
                        <small id="emailHelp" class="form-text text-muted">Nunca vamos compartilhar seu email, com ninguém.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Senha(*)</label>
                        <input type="password" class="form-control" placeholder="Senha" name="password">
                    </div>
                <button type="submit" class="btn btn-primary">Salvar usuário</button>
            </form>
        </div>
    
<?php require VIEWS . '/includes/footer.phtml'; ?>