<?php require VIEWS . '/includes/header.phtml'; ?>

        <div class="row mb-3">
            <div class="">
                <h1>Editar produtos</h1>
            </div>
            <a href="<?=HOME . '/admin/categories/list';?>" class="btn btn-md btn-danger mb-3 ml-auto">
                Voltar
            </a>
        </div>
        <div class="row">
            <?php require VIEWS . '/includes/message.phtml'; ?>
        </div>
        <div class="col-md-12">
            <form action="<?=HOME . '/admin/categories/edit'?>" method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nome</label>
                        <input type="text" class="form-control" placeholder="Nome" name="name" value="<?=$category['name']?>">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Descrição</label>
                        <input type="text" class="form-control" placeholder="Descrição" name="description" value="<?=$category['description']?>">
                    </div>

                <input type="hidden" name="id" value="<?=$category['id'];?>">
                <button type="submit" class="btn btn-primary">Salvar Categoria</button>
            </form>

            </div>
        </div>
    
<?php require VIEWS . '/includes/footer.phtml'; ?>