<?php require VIEWS . '/includes/header.phtml'; ?>

        <div class="row mb-3">
            <div class="">
                <h1>Categorias</h1>
            </div>
            <a href="<?=HOME . '/admin/categories/save';?>" class="btn btn-md btn-primary mb-3 ml-auto">
                Criar Categoria
            </a>
        </div>
        <div class="row">
            <?php require VIEWS . '/includes/message.phtml'; ?>
        </div>
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Criado Em</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($categories as $category) { ?>
                    <tr>
                        <td><?=$category['id']?></td>
                        <td><?=$category['name']?></td>
                        <td><?=$category['created_at']?></td>
                        <td>
                            <a href="<?=HOME . '/admin/categories/edit/'. $category['id'] ;?>" class="btn btn-sm btn-warning">Editar</a>
                            <a href="<?=HOME . '/admin/categories/remove/'. $category['id'] ;?>" class="btn btn-sm btn-danger">Remover</a>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    
<?php require VIEWS . '/includes/footer.phtml'; ?>